pacman -S libx11 
pacman -S libxcomposite 
pacman -S libxdamage 
pacman -S libxfixes 
pacman -S libXext 
pacman -S libxrender 
pacman -S libXrandr 
pacman -S libXinerama
pacman -S pkg-config
pacman -S make
pacman -S xproto
pacman -S x11proto
pacman -S sh
pacman -S xprop,xwininfo
pacman -S x11-utils
pacman -S libpcre
pacman -S libconfig
pacman -S libdrm
pacman -S libGL
pacman -S libdbus 
pacman -S asciidoc
